# Generated by Django 4.0.6 on 2022-07-21 02:37

from django.db import migrations


def populate_status(apps, schemaeditor):
    statuss = {
        "pending review":"content is waiting on review",
        "published":"content was published",
        "revision":"content was sent back for revisions",
        "denied":"content was denied",
        "draft":"content is currently in draft stage",
    }
    Status = apps.get_model("articles","status")
    for name, desc in statuss.items():
        section_obj = Status(name=name, description=desc)
        section_obj.save()




class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_status_article_status'),
    ]

    operations = [
        migrations.RunPython(populate_status),
    ]
